#ifndef CABOOSE_PLATFORM_SYSCALL_TABLE_H
#define CABOOSE_PLATFORM_SYSCALL_TABLE_H

#define SYSCALL_CREATE 0
#define SYSCALL_MYTID 1
#define SYSCALL_MYPARENTTID 2
#define SYSCALL_PASS 3
#define SYSCALL_EXIT 4
#define SYSCALL_SEND 5
#define SYSCALL_RECEIVE 6
#define SYSCALL_REPLY 7
#define SYSCALL_ASYNC_SEND 8
#define SYSCALL_ASYNC_RECEIVE 9
#define SYSCALL_AWAITEVENT 10
#define SYSCALL_ASSERT 11

#endif
